config/routes.rb
Rails.application.routes.draw do
  resources :cars
  root "cars#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :current_car, only: [:show, :edit, :update, :destroy]

  def index
    @cars = Car.all
  end

  def show

  end

  def new
    @cars = Car.new
  end

  def edit
    
  end

  def create
    @cars = Car.create(car_params)
    redirect_to cars_path
  end

  def update
    @cars = Car.find(params[:id])
    @cars.update(car_params)

    redirect_to car_path(@cars)
  end

  
  def destroy
    @cars = Car.find(params[:id])
    @cars.destroy

    redirect_to cars_path
  end


  private

  def car_params
    params.require(:car).permit(:name, :year)
  end

  def current_car
    @cars = Car.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/edit.html.erb
<h1>Cars</h1>
<h3>Update Car Details</h3>
<%= form_with model: @cars do |form| %>
  <%= form.text_field :name, placeholder: "name" %>
  <%= form.text_field :year, placeholder: "year" %>
  <%= form.submit %>
<% end %>

app/views/cars/index.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <span class="navbar-brand mb-0 h1">Cars</span>
  </div>
</nav>



<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">List</h5>
    <table>
  <% @cars.each do |car| %>
    <tr>
      <td><%= link_to car.name, car_path(car) %></td>
      <td><%= button_to 'Edit', edit_car_path(car), method: 'get'%></td>
      <td><%= button_to 'Remove', car_path(car), method: 'delete', data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>
  </div>
</div>

<button class="btn btn-light"><%= link_to "Add a New CAR", new_car_path %></button>

app/views/cars/new.html.erb
<h1>Cars</h1>

<h3>Register a Car</h3>
<%= form_with model: @cars do |form| %>
  <%= form.text_field :name, placeholder: "name" %>
  <%= form.text_field :year, placeholder: "year" %>
  <%= form.submit %>
<% end %>

app/views/cars/show.html.erb
<h1>Cars</h1>

<h1><%= @cars.name %></h1>
<h4>"<%= @cars.year %>"</h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>